### ISSUE TITLE
Documentor.jl Skeleton

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/GasModels.jl#15]
Probably want to setup Documentor.jl.  Even with just some basic.

This is a good example of a minimalist Documentor setup, https://github.com/lanl-ansi/Katana.jl/tree/master/docs

**Comment by rb004f** [comment]
Note: Also update travis.yml so that it builds the docs

**Comment by ccoffrin** [comment]
Seems to be working, magic? https://lanl-ansi.github.io/GasModels.jl/latest/

**Comment by ccoffrin** [comment]
In this skeleton I recomend replacing everything under, `Library` with a page that simply calls autodocs.  For example see, https://github.com/lanl-ansi/Katana.jl/blob/master/docs/src/library.md

Initially this will be much easier to maintain that a custom organization, like the one used in PowerModels.jl.

**Comment by rb004f** [comment]
I think I like the PowerModels organization, so willing to customize for now
