### ISSUE TITLE
Rename models to represent physics rather than mathprograming

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/GasModels.jl#158]
For example, NLP becomes WP (Weymouth instead of nonlinear program)

**Comment by rb004f** [comment]
Suggested naming conventions

GasModels
- WP (full Weymouth physics)
- WPSOC (convex relaxation of Weymouth physics)
- WPA (linear approximation of Weymouth physics)
- ...

Problem Formulations
- gf/ogf/... (nominal formulations, say the NLP version)
- gf_df/opf_df/... (formulations using edge flow disjunction)

**Comment by rb004f** [comment]
@ccoffrin @kaarthiksundar @pseudocubic @tasseff  Can I get your thoughts/suggestions on the proposed renaming here?  I am planning to resolve this issue next week (finally getting around to writing the GasModels software paper, so I need to finalize our names)

NLP          -> WP (Weymouth Physics)
MINLP   -> DWP (Disjunctive Weymouth Physics)
MISOCP -> CRDWP (Convex relaxation of the disjunctive weymouth physics)
MIP -> LRDWP (Linear relaxation of disjunctive weymouth physics)
LP -> LRWP (Linear relaxation of the weymouth physics)

**Comment by ccoffrin** [comment]
On a note related to this, this formulation doc page has been very useful in PowerModels, https://lanl-ansi.github.io/PowerModels.jl/stable/formulation-details/ you might conisider add similar docs here as well.

**Comment by tasseff** [comment]
I think if there are plans to eventually add other models of the gas network physics (e.g., the Panhandle equation), this makes sense. Otherwise, I think the "W" labels in each new renaming might be redundant.

**Comment by rb004f** [comment]
Agreed. We have lightweight formulations page, but we'lll flesh it out.

**Comment by rb004f** [comment]
No near term plans to add a panhandle implementation, but I want to add the "W" so that we don't box ourselves into corner should we (or someone else in the community) decide to add alternate physics.

**Comment by tasseff** [comment]
Okay, that makes sense. They sound good to me, then.
