### ISSUE TITLE
Test REQUIRE

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/GasModels.jl#17]
In the test/REQUIRE includes,
```
AmplNLWriter
CoinOptServices
```
but in runtests there are guards of the form,
```
if (Pkg.installed("AmplNLWriter") != nothing && Pkg.installed("CoinOptServices") != nothing)
...
end
```
If AmplNLWriter, CoinOptServices remain in REQUIRE, these guards are not need.  Otherwise AmplNLWriter, CoinOptServices should be removed from REQUIRE.

On a side note, I briefly used AmplNLWriter, CoinOptServices in the PowerModels CI, but pulling in the packages ended up taking so long the CI ran out of time!  So I stopped using them.

**Comment by rb004f** [comment]
Addressed in most recent merge
