### ISSUE TITLE
Compatible with InfrastructureModels v0.5

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/GasModels.jl#180]
@kaarthiksundar @pseudocubic how close are we to being compatible with infrastructure models v0.5?

**Comment by ccoffrin** [comment]
FYI, the breaking change was very minor, https://github.com/lanl-ansi/InfrastructureModels.jl/commit/a2f2089ac4dcb9998c3a2c03adf49513e36d309c

**Comment by pseudocubic** [comment]
Seems like v0.7 will be compatible, all tests pass on my local machine with InfrastructureModels v0.5. 

We can roll it out in the v0.7 release, which is slated for this sprint. @kaarthiksundar is working on it already
