### ISSUE TITLE
Fix Package Installed Checks

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/GasModels.jl#22]
To address the request here,
https://github.com/JuliaLang/METADATA.jl/pull/11108

Update the code here,
https://github.com/lanl-ansi/GasModels.jl/blob/0508f624c4f15b7ebd9a25faa4237b998225d8b5/src/core/solution.jl#L103

to be something like this,
https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/solution.jl#L155

**Comment by rb004f** [comment]
Removed installation checks from the current code base

**Comment by ccoffrin** [comment]
@rb004f great!  Follow the attobot steps to update the release and put a note in the metadata PR to let the maintainers know the comment has been addressed.

**Comment by rb004f** [comment]
@ccoffrin Done (I think)
