### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/GasModels.jl#31]
Currently, GasModels. jl assumes all input is in the correct units.  We need to support different types of units and have "make_per_unit" like function to normalize everything into the correct units.

**Comment by rb004f** [comment]
@ccoffrin Discussion to start. Do we want to support multiple units (i.e. meters vs. miles, psi vs. bars) that we then non dimensionalize?  I am inclined to only support one until we see a need to support multiple

**Comment by ccoffrin** [comment]
What has worked well in the power context is that the internal data supports one set of standard units, which can be converted to per-unit and back.  When parsing different formats the units are converted to the standard units or per-unit.  I would recomend going in this direction here as well.

As a general rule I would try to standardize around scientific units over imperial units, unless there is a compelling reason not to (e.g. when there is a consistent practices across science and industry).

**Comment by rb004f** [comment]
I think standardizing on SI is fine.  The benchmarks I use for unit testing are in SI or a unit of SI. Conversions are easy to do.
