### ISSUE TITLE
JuMP Version

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/GasModels.jl#5]
Probably extending the JuMP version to `JuMP 0.17 0.19-` will still be fine.  The METADATA managers prefer the widest possible version bounds.

**Comment by ccoffrin** [comment]
Make sure to be testing on Julia 0.5 and Julia 0.6 in Travis.  JuMP 0.18 only applies to Julia 0.6.

**Comment by rb004f** [comment]
Jump version 6 added to test
