### ISSUE TITLE
Explore removing qlfirm as a field

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/GasModels.jl#58]
Supporting the concepts of both qlfirm and qlmin/qlmax seems counter intuitive to many people. However, there are some use cases that needed both of these concept. Now that there is support for multiple loads at a junction, it is time to revisit this.  It might be possible to support these use cases with multiple loads.

**Comment by ccoffrin** [comment]
It might be good to have a general concept of dispatch able and non-dispatable loads, both in Power and Gas.  Then you can break these into separate explicit components.

**Comment by rb004f** [comment]
Worth a discussion on how to do this.  For some, min = max implies non-dispatchable loads.  Certainly, the current approach of allowing dispatchable and non dispatchable loads to be modeled as a single component seems to be counter-intuitive.

**Comment by rb004f** [comment]
@ccoffrin @kaarthiksundar This has been completed and merged into the master branch
