### ISSUE TITLE
Problem in the definition of run_soc_gf and run_nl_gf

### ISSUE THREAD

**Issue by cvr** [lanl-ansi/GasModels.jl#68]
Hi,

I believe functions `run_soc_gf` and `run_nl_gf` have a misspell on their definition, calling `run_pf` instead of `run_gf`. In file [GasModels.jl/src/prob/gf.jl](https://github.com/lanl-ansi/GasModels.jl/blob/master/src/prob/gf.jl) one finds the following functions:
```
" entry point into running the gas flow feasability problem "
function run_gf(file, model_constructor, solver; kwargs...)
    return run_generic_model(file, model_constructor, solver, post_gf; kwargs...) 
end

""
function run_soc_gf(file, solver; kwargs...)
    return run_pf(file, MISOCPGasModel, solver; kwargs...)
end

""
function run_nl_gf(file, solver; kwargs...)
    return run_pf(file, MINLPGasModel, solver; kwargs...)
end
```

When using GasModels in Julia and after defining a solver (with Pavito), executing `run_soc_gf("../test/data/gaslib-40.json", solver)` will yield an error whilst running `run_soc_gf("../test/data/gaslib-40.json", MISOCPGasModel, solver)` will return results. Both `run_soc_gf` and `run_nl_gf` call function `run_pf` which is undefined in the remainder of the source code.

**Comment by rb004f** [comment]
Thanks for the catch.  You are correct, the code should call run_gf, not run_pf.  We have updated the code
