### ISSUE TITLE
Tidy Whitespace

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/GasModels.jl#75]
There is extra white space characters throughout the code.

**Comment by rb004f** [comment]
@ccoffrin Can you provide more details/examples of what you are seeing?

**Comment by rb004f** [comment]
@ccoffrin what were you looking for here?

**Comment by pseudocubic** [comment]
he probably is referring to whitespace at the end of lines, too many lines at the end of files, consistent number of lines between functions, etc.

**Comment by ccoffrin** [comment]
That's right, check if your editor has the ability to show whitespace and you will see what this is about.
