### ISSUE TITLE
Constraint Return Values

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/GasModels.jl#9]
Consider removing the constraint return values, e.g.,
```
c1 = @constraint(gm.model, -(1-yp)*gm.ref[:max_flow] <= f)
c2 = @constraint(gm.model, f <= (1-yn)*gm.ref[:max_flow])
return Set([c1, c2])   
```
In PowerModels these were not being used anyone and they were causing a performance issue.  So I removed them.

**Comment by rb004f** [comment]
Done
